# Generated by Django 6.0.4 on 2026-05-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acusado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Acusados',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Armas',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agencia', models.CharField(max_length=20, unique=True)),
                ('data_ingres', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Perfil d'agent",
                'verbose_name_plural': "Perfils d'agents",
            },
        ),
        migrations.CreateModel(
            name='Cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(blank=True, max_length=200)),
                ('intents_max', models.PositiveSmallIntegerField(default=5)),
                ('estat', models.CharField(choices=[('en_curs', 'En curs'), ('resolt', 'Resolt'), ('arxivat', 'Arxivat')], default='en_curs', max_length=12)),
                ('iniciat_el', models.DateTimeField(auto_now_add=True)),
                ('finalitzat_el', models.DateTimeField(blank=True, null=True)),
                ('segons_acumulats', models.PositiveIntegerField(default=0)),
                ('solucio_acusado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CasoAbierto.acusado')),
                ('solucio_arma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CasoAbierto.arma')),
                ('solucio_lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CasoAbierto.lugar')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='CasoAbierto.perfilagent')),
            ],
            options={
                'verbose_name': 'Cas',
                'verbose_name_plural': 'Casos',
                'ordering': ['-iniciat_el'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('resultat', models.CharField(choices=[('correcte', 'Correcte'), ('parcial', 'Parcialment correcte'), ('incorrecte', 'Incorrecte')], max_length=12)),
                ('encerta_acusado', models.BooleanField(default=False)),
                ('encerta_arma', models.BooleanField(default=False)),
                ('encerta_lugar', models.BooleanField(default=False)),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('segons_des_inici', models.PositiveIntegerField(default=0)),
                ('acusado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CasoAbierto.acusado')),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CasoAbierto.arma')),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='CasoAbierto.cas')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CasoAbierto.lugar')),
            ],
            options={
                'verbose_name': 'Intent',
                'verbose_name_plural': 'Intents',
                'ordering': ['cas', 'numero'],
                'unique_together': {('cas', 'numero')},
            },
        ),
    ]
